# GitHub Copilot Configuration

# This file configures GitHub Copilot behavior for the repository
# For more information, see: https://docs.github.com/en/copilot

# Enable Copilot for this repository
enabled: true

# Configure suggestion preferences
suggestions:
  # Show suggestions for comments
  comments: true
  
  # Show suggestions for code
  code: true
  
  # Show suggestions for documentation
  documentation: true

# Configure language-specific settings
languages:
  # Configure behavior for specific languages
  # Examples:
  # python:
  #   enabled: true
  #   style: "pep8"
  # javascript:
  #   enabled: true
  #   style: "airbnb"
  # typescript:
  #   enabled: true
  #   style: "standard"

# Additional settings
settings:
  # Enable inline suggestions
  inline_suggestions: true
  
  # Enable ghost text
  ghost_text: true
  
  # Auto-completion trigger
  auto_trigger: true
